apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app
  labels:
    app: go-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-app
  template:
    metadata:
      labels:
        app: go-app
      annotations:
        # Enable eBPF auto-instrumentation for Go
        instrumentation.opentelemetry.io/inject-go: "true"
        # REQUIRED: Path to Go binary (must be annotation, not env var!)
        # Adjust this to your binary path inside the container
        instrumentation.opentelemetry.io/otel-go-auto-target-exe: "/app/main"
    spec:
      # Required for eBPF: allows sidecar to access the Go process
      shareProcessNamespace: true
      containers:
      - name: go-app
        image: your-go-app:latest  # Replace with your Go application image
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        env:
        # Optional: Override default service name
        - name: OTEL_SERVICE_NAME
          value: "my-go-service"

---
# Service for the Go application
apiVersion: v1
kind: Service
metadata:
  name: go-app
spec:
  selector:
    app: go-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP
